using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Persistence.Migrations
{
    /// <inheritdoc />
    public partial class Init2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "UserOperationClaims",
                keyColumn: "Id",
                keyValue: new Guid("0a10c8f5-0ab7-48fd-8759-b2749c8e3746")
            );

            migrationBuilder.DeleteData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("b2b04242-1902-4d80-8345-885be6dac93f")
            );

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[]
                {
                    "Id",
                    "AuthenticatorType",
                    "CreatedDate",
                    "DateOfBirth",
                    "DeletedDate",
                    "Email",
                    "FirstName",
                    "LastName",
                    "NationalIdentity",
                    "PasswordHash",
                    "PasswordSalt",
                    "UpdatedDate",
                    "UserName"
                },
                values: new object[]
                {
                    new Guid("3030e858-6aac-40c6-915c-38c53ea45930"),
                    0,
                    new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                    new DateTime(2024, 3, 25, 2, 48, 31, 891, DateTimeKind.Local).AddTicks(3087),
                    null,
                    "berker@ertan.com",
                    "Berker",
                    "Ertan",
                    "TC12312",
                    new byte[]
                    {
                        133,
                        140,
                        131,
                        45,
                        67,
                        107,
                        219,
                        34,
                        155,
                        194,
                        196,
                        154,
                        53,
                        237,
                        8,
                        173,
                        178,
                        13,
                        52,
                        89,
                        48,
                        184,
                        211,
                        167,
                        214,
                        87,
                        23,
                        77,
                        165,
                        244,
                        42,
                        168,
                        222,
                        21,
                        144,
                        114,
                        137,
                        68,
                        146,
                        124,
                        222,
                        255,
                        136,
                        112,
                        2,
                        207,
                        59,
                        219,
                        111,
                        82,
                        26,
                        58,
                        245,
                        78,
                        211,
                        41,
                        227,
                        73,
                        62,
                        150,
                        79,
                        108,
                        242,
                        50
                    },
                    new byte[]
                    {
                        132,
                        82,
                        206,
                        46,
                        226,
                        185,
                        227,
                        33,
                        112,
                        52,
                        161,
                        26,
                        250,
                        94,
                        191,
                        254,
                        83,
                        194,
                        241,
                        253,
                        170,
                        135,
                        215,
                        142,
                        160,
                        73,
                        111,
                        191,
                        160,
                        94,
                        207,
                        154,
                        160,
                        210,
                        54,
                        72,
                        244,
                        73,
                        224,
                        62,
                        235,
                        14,
                        243,
                        11,
                        82,
                        242,
                        32,
                        194,
                        101,
                        192,
                        48,
                        251,
                        186,
                        100,
                        209,
                        167,
                        150,
                        155,
                        248,
                        117,
                        241,
                        231,
                        36,
                        218,
                        180,
                        56,
                        6,
                        38,
                        234,
                        4,
                        27,
                        184,
                        154,
                        233,
                        82,
                        61,
                        26,
                        121,
                        34,
                        227,
                        248,
                        62,
                        12,
                        202,
                        111,
                        14,
                        8,
                        148,
                        79,
                        250,
                        54,
                        14,
                        21,
                        145,
                        119,
                        180,
                        116,
                        9,
                        155,
                        117,
                        193,
                        29,
                        222,
                        33,
                        47,
                        131,
                        232,
                        160,
                        229,
                        128,
                        187,
                        162,
                        207,
                        242,
                        87,
                        254,
                        71,
                        183,
                        234,
                        0,
                        228,
                        26,
                        250,
                        33,
                        28,
                        193,
                        91,
                        166
                    },
                    null,
                    "berkerertan"
                }
            );

            migrationBuilder.InsertData(
                table: "UserOperationClaims",
                columns: new[] { "Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId" },
                values: new object[]
                {
                    new Guid("c7250db4-f620-4fb9-b736-b71470783009"),
                    new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                    null,
                    1,
                    null,
                    new Guid("3030e858-6aac-40c6-915c-38c53ea45930")
                }
            );
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "UserOperationClaims",
                keyColumn: "Id",
                keyValue: new Guid("c7250db4-f620-4fb9-b736-b71470783009")
            );

            migrationBuilder.DeleteData(
                table: "Users",
                keyColumn: "Id",
                keyValue: new Guid("3030e858-6aac-40c6-915c-38c53ea45930")
            );

            migrationBuilder.InsertData(
                table: "Users",
                columns: new[]
                {
                    "Id",
                    "AuthenticatorType",
                    "CreatedDate",
                    "DateOfBirth",
                    "DeletedDate",
                    "Email",
                    "FirstName",
                    "LastName",
                    "NationalIdentity",
                    "PasswordHash",
                    "PasswordSalt",
                    "UpdatedDate",
                    "UserName"
                },
                values: new object[]
                {
                    new Guid("b2b04242-1902-4d80-8345-885be6dac93f"),
                    0,
                    new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                    new DateTime(2024, 3, 25, 2, 35, 4, 182, DateTimeKind.Local).AddTicks(4830),
                    null,
                    "berker@ertan.com",
                    "Berker",
                    "Ertan",
                    "12312",
                    new byte[]
                    {
                        204,
                        79,
                        20,
                        221,
                        191,
                        1,
                        188,
                        205,
                        207,
                        71,
                        47,
                        197,
                        188,
                        72,
                        195,
                        71,
                        149,
                        27,
                        80,
                        26,
                        12,
                        84,
                        79,
                        154,
                        42,
                        2,
                        92,
                        0,
                        226,
                        244,
                        25,
                        200,
                        150,
                        111,
                        101,
                        87,
                        81,
                        15,
                        195,
                        148,
                        255,
                        121,
                        95,
                        126,
                        111,
                        217,
                        124,
                        247,
                        18,
                        169,
                        160,
                        252,
                        244,
                        184,
                        232,
                        199,
                        89,
                        119,
                        217,
                        116,
                        167,
                        122,
                        80,
                        212
                    },
                    new byte[]
                    {
                        239,
                        252,
                        229,
                        79,
                        17,
                        62,
                        91,
                        133,
                        225,
                        169,
                        69,
                        56,
                        36,
                        230,
                        162,
                        239,
                        199,
                        157,
                        116,
                        228,
                        8,
                        234,
                        181,
                        245,
                        90,
                        116,
                        70,
                        225,
                        36,
                        147,
                        224,
                        69,
                        2,
                        10,
                        110,
                        86,
                        143,
                        86,
                        131,
                        225,
                        123,
                        186,
                        192,
                        0,
                        175,
                        74,
                        79,
                        170,
                        125,
                        110,
                        86,
                        225,
                        12,
                        14,
                        5,
                        125,
                        166,
                        173,
                        10,
                        110,
                        80,
                        43,
                        94,
                        218,
                        63,
                        126,
                        44,
                        3,
                        116,
                        157,
                        107,
                        19,
                        246,
                        171,
                        184,
                        183,
                        96,
                        247,
                        250,
                        149,
                        194,
                        71,
                        189,
                        171,
                        135,
                        188,
                        181,
                        115,
                        116,
                        86,
                        193,
                        4,
                        117,
                        197,
                        156,
                        92,
                        177,
                        2,
                        67,
                        5,
                        4,
                        226,
                        58,
                        166,
                        142,
                        0,
                        139,
                        79,
                        237,
                        151,
                        126,
                        106,
                        55,
                        111,
                        185,
                        168,
                        248,
                        41,
                        6,
                        40,
                        253,
                        194,
                        1,
                        223,
                        97,
                        214,
                        232,
                        36
                    },
                    null,
                    "berkerertan"
                }
            );

            migrationBuilder.InsertData(
                table: "UserOperationClaims",
                columns: new[] { "Id", "CreatedDate", "DeletedDate", "OperationClaimId", "UpdatedDate", "UserId" },
                values: new object[]
                {
                    new Guid("0a10c8f5-0ab7-48fd-8759-b2749c8e3746"),
                    new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                    null,
                    1,
                    null,
                    new Guid("b2b04242-1902-4d80-8345-885be6dac93f")
                }
            );
        }
    }
}
